home/urls.py
# -*- coding: utf-8 -*-
"""testapp URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url

from home import views

urlpatterns = (
    url(r'^$', views.index, name='index'),
)

urls.py
# -*- coding: utf-8 -*-
"""URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('blueapps.account.urls')),
    url(r'^', include('home.urls', namespace='home')),
]

templates/_foot_js.html
<!-- scripts -->
<script src="{{ STATIC_URL }}js/jquery-1.10.2.min.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}js/plugins/sweetalert/sweetalert.min.js"></script>
<script src="{{ STATIC_URL }}js/plugins/datatables/datatables.min.js"></script>
<script src="{{ STATIC_URL }}js/plugins/toastr/toastr.min.js"></script>
<script src="{{ STATIC_URL }}js/plugins/kendoui/kendo.all.min.js"></script>
<script type="text/javascript">
    var app_code = "{{ APP_CODE }}";			// 在蓝鲸系统里面注册的"应用编码"
    var site_url = "{{ SITE_URL }}";			// app的url前缀,在ajax调用的时候，应该加上该前缀
</script>
<script src="{{ STATIC_URL }}js/csrftoken.js?v={{ STATIC_VERSION }}"></script>

templates/_head_css.html
<!-- css file -->
<link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
<link href="{{ STATIC_URL }}css/font-awesome.min.css" rel="stylesheet">
<link href="{{ STATIC_URL }}css/plugins/toastr/toastr.min.css" rel="stylesheet">
<link href="{{ STATIC_URL }}css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
<link href="{{ STATIC_URL }}css/plugins/vaildator/jquery.validator.css" rel="stylesheet">
<link href="{{ STATIC_URL }}css/plugins/datatables/datatables.min.css" rel="stylesheet">
<link href="{{ STATIC_URL }}css/sb-admin.css" rel="stylesheet">
<link href="{{ STATIC_URL }}css/sb-bk-theme.css" rel="stylesheet">
<link href="{{ STATIC_URL }}css/bk.css" rel="stylesheet">

templates/_navigation.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">
            <i class="fa fa-leaf f20 mr5"></i>
            运维管理系统
        </a>
    </div>
    <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> admin <b
                    class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <a href="#"><i class="fa fa-fw fa-user"></i> 用户</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-gear"></i> 设置</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-power-off"></i> 退出</a>
                </li>
            </ul>
        </li>
    </ul>
    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
            <li class="active">
                <a href="{% url 'home:index' %}"><i class="fa fa-fw fa-dashboard"></i> 数据概览</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-fw fa-edit"></i> 资产管理</a>
            </li>
            <li>
                <a href="#" data-toggle="collapse" data-target="#demo2"><i class="fa fa-fw fa-arrows-v"></i>
                    作业中心 <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="demo2" class="collapse">
                    <li>
                        <a href="#">任务列表 </a>
                    </li>
                    <li>
                        <a href="#">批量命令</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- /.navbar-collapse -->
</nav>

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">
    <title>运维管理系统</title>
    <link rel="shortcut icon" href="{{ STATIC_URL }}img/facio.ico" type="image/x-icon">
    {% include '_head_css.html' %}
    {% block custom_head_css %}{% endblock %}
</head>

<body>
<div id="wrapper">
    {% include '_navigation.html' %}
    <div id="page-wrapper">
        {% block content %}{% endblock %}
    </div>
</div>

</body>
{% include '_foot_js.html' %}
{% block custom_foot_js %}{% endblock %}
</html>